version: "3"
services:
  nestjs-app:
    build:
      context: .
      dockerfile: ./docker/nestjs-app/Dockerfile
    volumes:
      - ./nestjs-app:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - ./nestjs-app/.env
    tty: true

  slack-app:
    build:
      context: .
      dockerfile: ./docker/slack-app/Dockerfile
    volumes:
      - ./slack-app:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4000:4000"
    env_file:
      - ./slack-app/.env
    tty: true
