version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./app:/usr/src/app
    ports:
      - "3000:3000"
    entrypoint:
      - sh
    command:
      - -c
      - |
        npm install
        npm run start:dev
    tty: true

  slack-app:
    image: node:22.13
    working_dir: /usr/src/app
    volumes:
      - ./slack-app:/usr/src/app
    ports:
      - "4000:4000"
    env_file:
      - ./slack-app/.env
    entrypoint:
      - sh
    command:
      - -c
      - |
        npm install
        npm run start:dev
    tty: true
