version: "3"
services:
  app:
    image: node:22.13
    working_dir: /usr/src/app
    volumes:
      - ./app:/usr/src/app
    ports:
      - "3000:3000"
    entrypoint:
      - sh
    command:
      - -c
      - |
        npm install
        npm run start:dev
    tty: true
