version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./app:/usr/src/app
    ports:
      - "3000:3000"
    entrypoint:
      - sh
    command:
      - -c
      - |
        npm install
        npm run start:dev
    tty: true
